### ISSUE TITLE
Was the android sdk level change in 1.0.1 intentional?

### ISSUE THREAD

**Issue by idoco** [cocoahero/android-geojson#8]
Hi Jonathan,
I had my project configured with the following Gradle dependency:
```gradle
compile 'com.cocoahero.android:geojson:1.0.+@aar'
```
And today my project compilation failed over the sdk level change:
```log
com.cocoahero.android\geojson\1.0.1\AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='19'> but library uses targetSdkVersion='22' :app:processDebugManifest FAILED
```
For now I've changed my dependency to:
```gradle
compile 'com.cocoahero.android:geojson:1.0.0'
```
Thanks.

**Comment by cocoahero** [comment]
It was intentional, being that it's being compiled against the latest SDK, there shouldn't be any reason not to target the latest SDK (from the libraries point of view).

That being said, I'm not able to replicate this issue on my side with a new project and latest build tools and gradle plugin.

What version of the gradle plugin and build tools are you using? According to the new manifest merger docs, this shouldn't be an issue.

https://code.google.com/p/android/issues/detail?id=56182

http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger

**Comment by idoco** [comment]
Yeah, I'm using IntelliJ 13 with the  'default gradle wrapper', it might be using an older version.
I'm not sure that this is a real issue, I just didn't have any other place to ask this question :)

**Comment by cocoahero** [comment]
Make sure your android gradle plugin is at least `1.0.0` and see if that fixes it. My `build.gradle` has something like this in it.

```
dependencies {
        classpath 'com.android.tools.build:gradle:1.1.3'
}```
